---

- hosts: db 
  remote_user: root

  tasks:
  - name: install zabbix 4.2 repo
    yum:
      name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm  
      state: present

  - name: install zabbix-agent
    yum: name=zabbix-agent state=latest

  - name: copy zabbix configuration file
    copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  
  - name: Start zabbix-agent
    service: name=zabbix-agent state=restarted enabled=yes
